version: 2

builds:
  - skip: true

changelog:
  use: github
  sort: asc
  groups:
    - title: "New Features and updates"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Documentation updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 20
    - title: Other work
      order: 999
  filters:
    exclude:
      - ^test
      - changelog
      - typo
      - Readme
      - ^Merge pull request
      - ^Merge branch

announce:
  linkedin:
    # Templates: allowed (since v2.6).
    enabled: true
    # Message to use while publishing.
    #
    # Default: '{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}'.
    # message_template: "Awesome project {{.Tag}} is out!"

  mastodon:
    # Whether its enabled or not.
    #
    # Templates: allowed (since v2.6).
    enabled: true

    # Message to use while publishing.
    #
    # Default: '{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}'.
    # Templates: allowed.

    # Mastodon server URL.
    server: https://me.dm